// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bySum
DataFrame bySum(List ffValues, List ffBins);
RcppExport SEXP FeatureExtraction_bySum(SEXP ffValuesSEXP, SEXP ffBinsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type ffValues(ffValuesSEXP);
    Rcpp::traits::input_parameter< List >::type ffBins(ffBinsSEXP);
    __result = Rcpp::wrap(bySum(ffValues, ffBins));
    return __result;
END_RCPP
}
// byMax
DataFrame byMax(List ffValues, List ffBins);
RcppExport SEXP FeatureExtraction_byMax(SEXP ffValuesSEXP, SEXP ffBinsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type ffValues(ffValuesSEXP);
    Rcpp::traits::input_parameter< List >::type ffBins(ffBinsSEXP);
    __result = Rcpp::wrap(byMax(ffValues, ffBins));
    return __result;
END_RCPP
}
