# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.bySum <- function(ffValues, ffBins) {
    .Call('FeatureExtraction_bySum', PACKAGE = 'FeatureExtraction', ffValues, ffBins)
}

.byMax <- function(ffValues, ffBins) {
    .Call('FeatureExtraction_byMax', PACKAGE = 'FeatureExtraction', ffValues, ffBins)
}

