# @file PackageMaintenance
#
# Copyright 2017 Observational Health Data Sciences and Informatics
#
# This file is part of FeatureExtraction
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code
OhdsiRTools::formatRFolder()
OhdsiRTools::checkUsagePackage("FeatureExtraction")
OhdsiRTools::updateCopyrightYearFolder()

# Create manual and vignettes
shell("rm extras/FeatureExtraction.pdf")
shell("R CMD Rd2pdf ./ --output=extras/FeatureExtraction.pdf")

rmarkdown::render("vignettes/CreatingCustomCovariateBuilders.Rmd",
                  output_file = "../inst/doc/CreatingCustomCovariateBuilders.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/CreatingCovariatesUsingCohortAttributes.Rmd",
                  output_file = "../inst/doc/CreatingCovariatesUsingCohortAttributes.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

# Generate covariate settings function from template ----------------------
prespecAnalyses <- read.csv("inst/csv/PrespecAnalyses.csv", stringsAsFactors = FALSE)
otherParameters <- read.csv("inst/csv/OtherParameters.csv", stringsAsFactors = FALSE)
arguments <- data.frame(name = paste0("use", prespecAnalyses$analysisName),
                        defaultValue = "FALSE",
                        description = prespecAnalyses$description,
                        stringsAsFactors = FALSE)
arguments <- rbind(arguments, otherParameters[otherParameters$type == "days", c("name", "defaultValue", "description")])
arguments <- rbind(arguments, otherParameters[otherParameters$type == "common", c("name", "defaultValue", "description")])
arguments$defaultValue[arguments$defaultValue == "[]"] <- "c()"
arguments$defaultValue[arguments$defaultValue == "false"] <- "FALSE"
arguments$defaultValue[arguments$defaultValue == "true"] <- "TRUE"
roxygen <- paste(paste("#' @param", arguments$name, arguments$description), collapse = "\n")
argumentString <- paste(paste(arguments$name, "=", arguments$defaultValue), collapse = ",\n")
rCode <- readLines(file("extras/DefaultCovariateSettingsTemplate.R"))
rCode <- gsub("%warning%", "# This file has been autogenerated. Do not change by hand.", rCode)
rCode <- gsub("%temporal%", "FALSE", rCode)
rCode <- gsub("%roxygen%", roxygen, rCode)
rCode <- gsub("%arguments%", argumentString, rCode)
writeLines(rCode, "R/DefaultCovariateSettings.R")
OhdsiRTools::formatRFile("R/DefaultCovariateSettings.R")

covariateSettings <- createCovariateSettings(useDemographicsGender = TRUE, useDemographicsAge = TRUE, excludedCovariateConceptIds = c(1,2,3))
.toJson(covariateSettings)
covariateSettings <- convertPrespecSettingsToDetailedSettings(covariateSettings)
