# @file PackageMaintenance
#
# Copyright 2017 Observational Health Data Sciences and Informatics
#
# This file is part of FeatureExtraction
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code
OhdsiRTools::formatRFolder()
OhdsiRTools::checkUsagePackage("FeatureExtraction")
OhdsiRTools::updateCopyrightYearFolder()

# Create manual and vignettes
shell("rm extras/FeatureExtraction.pdf")
shell("R CMD Rd2pdf ./ --output=extras/FeatureExtraction.pdf")

rmarkdown::render("vignettes/CreatingCustomCovariateBuilders.Rmd",
                  output_file = "../inst/doc/CreatingCustomCovariateBuilders.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/CreatingCovariatesUsingCohortAttributes.Rmd",
                  output_file = "../inst/doc/CreatingCovariatesUsingCohortAttributes.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

# Generate covariate settings function from template ----------------------
featureSets <- read.csv("inst/csv/FeatureSets.csv")
camelCase <- function(x) {
  return(SqlRender::snakeCaseToCamelCase(gsub("_+", "_", gsub("[^a-z]", "_", tolower(x)))))
}
argumentNames <- camelCase(paste("use", featureSets$analysisName))
roxygen <- paste(paste("#' @param", argumentNames, featureSets$description), collapse = "\n")
arguments <- paste(paste(argumentNames, "= FALSE,"), collapse = "\n")
argumentsRoxygen <- paste(paste(argumentNames[featureSets$default == 1], "= TRUE"), collapse = ",\n#'             ")
rCode <- readLines(file("extras/DefaultCovariateSettingsTemplate.R"))
rCode <- gsub("%roxygen%", roxygen, rCode)
rCode <- gsub("%arguments%", arguments, rCode)
rCode <- gsub("%argumentsRoxygen%", argumentsRoxygen, rCode)
writeLines(rCode, "R/DefaultCovariateSettings.R")
OhdsiRTools::formatRFile("R/DefaultCovariateSettings.R")

# Generate concept-domain SQL from template -------------------------------
library(SqlRender)
template <- readSql("inst/sql/sql_server/ConceptDomainTemplate.sql")
warning <- "-- This file is automatically generated, do not edit by hand"
fillTemplateAndSave <- function(sql, fileName, ...) {
  x <- list(...)
  for (i in 1:length(x))
    sql <- gsub(paste0("@", names(x)[i]), x[[i]], sql)
  writeSql(sql, fileName)
}

fillTemplateAndSave(sql = template, 
                    fileName = "inst/sql/sql_server/ConditionOccurrence.sql",
                    warning = warning, 
                    domain_table = "condition_occurrence", 
                    domain_concept_id = "condition_concept_id",
                    domain_start_date = "condition_start_date",
                    domain_end_date = "condition_start_date",
                    domain_label = "Condition occurrence")

fillTemplateAndSave(sql = template, 
                    fileName = "inst/sql/sql_server/ConditionEra.sql",
                    warning = warning, 
                    domain_table = "condition_era", 
                    domain_concept_id = "condition_concept_id",
                    domain_start_date = "condition_era_start_date",
                    domain_end_date = "condition_era_end_date",
                    domain_label = "Condition era")

fillTemplateAndSave(sql = template, 
                    fileName = "inst/sql/sql_server/DrugExposure.sql",
                    warning = warning, 
                    domain_table = "drug_exposure", 
                    domain_concept_id = "drug_concept_id",
                    domain_start_date = "drug_exposure_start_date",
                    domain_end_date = "drug_exposure_start_date",
                    domain_label = "Drug exposure")

fillTemplateAndSave(sql = template, 
                    fileName = "inst/sql/sql_server/DrugEra.sql",
                    warning = warning, 
                    domain_table = "drug_era", 
                    domain_concept_id = "drug_concept_id",
                    domain_start_date = "drug_era_start_date",
                    domain_end_date = "drug_era_end_date",
                    domain_label = "Drug era")

fillTemplateAndSave(sql = template, 
                    fileName = "inst/sql/sql_server/ProcedureOccurrence.sql",
                    warning = warning, 
                    domain_table = "procedure_occurrence", 
                    domain_concept_id = "procedure_concept_id",
                    domain_start_date = "procedure_date",
                    domain_end_date = "procedure_date",
                    domain_label = "Procedure occurrence")

fillTemplateAndSave(sql = template, 
                    fileName = "inst/sql/sql_server/DeviceExposure.sql",
                    warning = warning, 
                    domain_table = "device_exposure", 
                    domain_concept_id = "device_concept_id",
                    domain_start_date = "device_exposure_start_date",
                    domain_end_date = "device_exposure_start_date",
                    domain_label = "Device exposure")

fillTemplateAndSave(sql = template, 
                    fileName = "inst/sql/sql_server/Measurement.sql",
                    warning = warning, 
                    domain_table = "measurement", 
                    domain_concept_id = "measurement_concept_id",
                    domain_start_date = "measurement_date",
                    domain_end_date = "measurement_date",
                    domain_label = "Measurement")

fillTemplateAndSave(sql = template, 
                    fileName = "inst/sql/sql_server/Observation.sql",
                    warning = warning, 
                    domain_table = "observation", 
                    domain_concept_id = "observation_concept_id",
                    domain_start_date = "observation_date",
                    domain_end_date = "observation_date",
                    domain_label = "Observation")



